language: generic
env:
  - COMPILER=smlnj PACKAGES="smlnj ml-yacc ml-ulex moreutils"
  - COMPILER=mlton PACKAGES="mlton moreutils"
  - COMPILER=sphinx SPHINXOPTS="-n -W" PACKAGES="python-sphinx"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes ${PACKAGES}
install:
  - git submodule init
  - git submodule update --init --recursive
  - pip install sphinx-rtd-theme
script:
  - ./script/test-${COMPILER}.sh

notifications:
  email: false
